### ISSUE TITLE
请同步 win32 源码分支

### ISSUE THREAD

**Issue by legendtang** [isombyt/zdcclient#1]
http://zdcclient.googlecode.com/svn/branches/win32/

原项目有这个分支的，请务必在 Google Code 下线之前同步，我可以协助维护

**Comment by isombyt** [comment]
win32分支已经推上去，但是考虑到win32版本与linux版本的差异，需要人工将linux分支的更新手工合并进去。

**Comment by legendtang** [comment]
@isombyt win32 版本有掉线问题，我已经 fork 了自己的一份改过验证的版本 [版本](https://github.com/legendtang/ZDClient_win32)
在刚刚已经邮件获得了原作者的授权，我看了下主要文件 win32 和 linux 基本没有交集，API 差得太多

你看是推到你这边还是你在 README.MD 单独写个 redirect？毕竟这个原分支本身也是有点问题的，而且不需要原来的文件。

我在我的 repo 里面已经写清楚了 Development Guide

**Comment by isombyt** [comment]
@legendtang 虽然说本来是推荐将共同的代码提取出来方便开发，但是这两个分住差异太大而且本项目的开发趋于停止，所以我觉得两个项目都作为独立的项目是可行的，我们互相在Readme加上link就好。

**Comment by legendtang** [comment]
@isombyt Agreed. 就这么办吧，我已经加上了 Link 了
